# permissions for end users to edit namespacecheckers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: component-operator
    app.kubernetes.io/managed-by: kustomize
  name: namespacechecker-editor-role
rules:
- apiGroups:
  - api.component.cloudsteak.com
  resources:
  - namespacecheckers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.component.cloudsteak.com
  resources:
  - namespacecheckers/status
  verbs:
  - get
