---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.component.cloudsteak.com
  resources:
  - namespacecheckers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.component.cloudsteak.com
  resources:
  - namespacecheckers/finalizers
  verbs:
  - update
- apiGroups:
  - api.component.cloudsteak.com
  resources:
  - namespacecheckers/status
  verbs:
  - get
  - patch
  - update
