apiVersion: api.component.cloudsteak.com/v1alpha1
kind: NamespaceChecker
metadata:
  labels:
    app.kubernetes.io/name: component-operator
    app.kubernetes.io/managed-by: kustomize
  name: namespacechecker-sample
spec:
  
