apiVersion: api.component.cloudsteak.com/v1alpha1
kind: NamespaceChecker
metadata:
  name: namespacechecker-sample
spec:
  namespaces:
  - ai-core
  - hana
  - redis
  configMapNames:
  - ai-backend-config
  configMapNamespace: ai-core
  secretNames:
  - ai-core
  - ai-ghcr-login-secret
  secretNamespace: ai-core
