//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceChecker) DeepCopyInto(out *NamespaceChecker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceChecker.
func (in *NamespaceChecker) DeepCopy() *NamespaceChecker {
	if in == nil {
		return nil
	}
	out := new(NamespaceChecker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceChecker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceCheckerList) DeepCopyInto(out *NamespaceCheckerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceCheckerList.
func (in *NamespaceCheckerList) DeepCopy() *NamespaceCheckerList {
	if in == nil {
		return nil
	}
	out := new(NamespaceCheckerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceCheckerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceCheckerSpec) DeepCopyInto(out *NamespaceCheckerSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigMapNames != nil {
		in, out := &in.ConfigMapNames, &out.ConfigMapNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecretsNames != nil {
		in, out := &in.SecretsNames, &out.SecretsNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceCheckerSpec.
func (in *NamespaceCheckerSpec) DeepCopy() *NamespaceCheckerSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceCheckerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceCheckerStatus) DeepCopyInto(out *NamespaceCheckerStatus) {
	*out = *in
	if in.NamespacesExist != nil {
		in, out := &in.NamespacesExist, &out.NamespacesExist
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigMapsExist != nil {
		in, out := &in.ConfigMapsExist, &out.ConfigMapsExist
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecretsExist != nil {
		in, out := &in.SecretsExist, &out.SecretsExist
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceCheckerStatus.
func (in *NamespaceCheckerStatus) DeepCopy() *NamespaceCheckerStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceCheckerStatus)
	in.DeepCopyInto(out)
	return out
}
